package server;

public enum Endpoint {
    GET_TASKS,
    GET_EPICS,
    GET_SUBTASKS,
    GET_TASK_BY_ID,
    GET_EPIC_BY_ID,
    GET_SUBTASK_BY_ID,
    GET_EPIC_SUBTASKS_ID,
    GET_PRIORITIZED_TASK,
    GET_HISTORY,

    POST_ADD_OR_UPDATE_TASK,
    POST_ADD_OR_UPDATE_EPIC,

    POST_ADD_OR_UPDATE_SUBTASK,
    DELETE_ALL_TASKS,
    DELETE_ALL_EPICS,
    DELETE_ALL_SUBTASKS,
    DELETE_TASK_BY_ID,
    DELETE_EPIC_BY_ID,
    DELETE_SUBTASK_BY_ID,
    UNKNOWN

}
